<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitattributes" />
    <None Remove=".gitignore" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
	<PackageReference Include="CppSharp" Version="1.1.5.3168" />
	<PackageReference Include="FParsec" Version="2.0.0-beta2" />
	<PackageReference Include="FParsec.CSharp" Version="12.6.0" />
  </ItemGroup>

</Project>
