namespace Flyleaf.FFmpeg;

public unsafe static partial class Raw
{
    // public static attribute_deprecated = __declspec(deprecated);
    // public static av_alias = __attribute__((may_alias));
    // public static av_alloc_size = (...);
    // public static av_always_inline = __forceinline;
    /// <summary>AV_BUFFER_FLAG_READONLY = (1 &lt;&lt; 0)</summary>
    public const int AV_BUFFER_FLAG_READONLY = 1 << 0;
    // public static av_builtin_constant_p = __builtin_constant_p;
    // public static av_ceil_log2 = av_ceil_log2_c;
    // public static AV_CEIL_RSHIFT = (a,b) (!av_builtin_constant_p(b) ? -((-(a)) >> (b)) : ((a) + (1<<(b)) - 1) >> (b));
    /// <summary>AV_CHANNEL_LAYOUT_2_1 = AV_CHANNEL_LAYOUT_MASK(3,  AV_CH_LAYOUT_2_1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_2_1 = AV_CHANNEL_LAYOUT_MASK(3, (ulong)ChannelFlags.Layout_2_1);
    /// <summary>AV_CHANNEL_LAYOUT_2_2 = AV_CHANNEL_LAYOUT_MASK(4,  AV_CH_LAYOUT_2_2)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_2_2 = AV_CHANNEL_LAYOUT_MASK(4, (ulong)ChannelFlags.Layout_2_2);
    /// <summary>AV_CHANNEL_LAYOUT_22POINT2 = AV_CHANNEL_LAYOUT_MASK(24, AV_CH_LAYOUT_22POINT2)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_22POINT2 = AV_CHANNEL_LAYOUT_MASK(24, (ulong)ChannelFlags.Layout_22POINT2);
    /// <summary>AV_CHANNEL_LAYOUT_2POINT1 = AV_CHANNEL_LAYOUT_MASK(3,  AV_CH_LAYOUT_2POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_2POINT1 = AV_CHANNEL_LAYOUT_MASK(3, (ulong)ChannelFlags.Layout_2POINT1);
    /// <summary>AV_CHANNEL_LAYOUT_3POINT1 = AV_CHANNEL_LAYOUT_MASK(4,  AV_CH_LAYOUT_3POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_3POINT1 = AV_CHANNEL_LAYOUT_MASK(4, (ulong)ChannelFlags.Layout_3POINT1);
    /// <summary>AV_CHANNEL_LAYOUT_3POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_3POINT1POINT2)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_3POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.Layout_3POINT1POINT2);
    /// <summary>AV_CHANNEL_LAYOUT_4POINT0 = AV_CHANNEL_LAYOUT_MASK(4,  AV_CH_LAYOUT_4POINT0)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_4POINT0 = AV_CHANNEL_LAYOUT_MASK(4, (ulong)ChannelFlags.Layout_4POINT0);
    /// <summary>AV_CHANNEL_LAYOUT_4POINT1 = AV_CHANNEL_LAYOUT_MASK(5,  AV_CH_LAYOUT_4POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_4POINT1 = AV_CHANNEL_LAYOUT_MASK(5, (ulong)ChannelFlags.Layout_4POINT1);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT0 = AV_CHANNEL_LAYOUT_MASK(5,  AV_CH_LAYOUT_5POINT0)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT0 = AV_CHANNEL_LAYOUT_MASK(5, (ulong)ChannelFlags.Layout_5POINT0);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT0_BACK = AV_CHANNEL_LAYOUT_MASK(5,  AV_CH_LAYOUT_5POINT0_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT0_BACK = AV_CHANNEL_LAYOUT_MASK(5, (ulong)ChannelFlags.Layout_5POINT0Back);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT1 = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_5POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT1 = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.Layout_5POINT1);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT1_BACK = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_5POINT1_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT1_BACK = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.Layout_5POINT1Back);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_5POINT1POINT2)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.Layout_5POINT1POINT2);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT1POINT2_BACK = AV_CHANNEL_LAYOUT_MASK(8, AV_CH_LAYOUT_5POINT1POINT2_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT1POINT2_BACK = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.Layout_5POINT1POINT2Back);
    /// <summary>AV_CHANNEL_LAYOUT_5POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(10, AV_CH_LAYOUT_5POINT1POINT4_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_5POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(10, (ulong)ChannelFlags.Layout_5POINT1POINT4Back);
    /// <summary>AV_CHANNEL_LAYOUT_6POINT0 = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_6POINT0)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_6POINT0 = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.Layout_6POINT0);
    /// <summary>AV_CHANNEL_LAYOUT_6POINT0_FRONT = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_6POINT0_FRONT)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_6POINT0_FRONT = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.Layout_6POINT0Front);
    /// <summary>AV_CHANNEL_LAYOUT_6POINT1 = AV_CHANNEL_LAYOUT_MASK(7,  AV_CH_LAYOUT_6POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_6POINT1 = AV_CHANNEL_LAYOUT_MASK(7, (ulong)ChannelFlags.Layout_6POINT1);
    /// <summary>AV_CHANNEL_LAYOUT_6POINT1_BACK = AV_CHANNEL_LAYOUT_MASK(7,  AV_CH_LAYOUT_6POINT1_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_6POINT1_BACK = AV_CHANNEL_LAYOUT_MASK(7, (ulong)ChannelFlags.Layout_6POINT1Back);
    /// <summary>AV_CHANNEL_LAYOUT_6POINT1_FRONT = AV_CHANNEL_LAYOUT_MASK(7,  AV_CH_LAYOUT_6POINT1_FRONT)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_6POINT1_FRONT = AV_CHANNEL_LAYOUT_MASK(7, (ulong)ChannelFlags.Layout_6POINT1Front);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT0 = AV_CHANNEL_LAYOUT_MASK(7,  AV_CH_LAYOUT_7POINT0)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT0 = AV_CHANNEL_LAYOUT_MASK(7, (ulong)ChannelFlags.Layout_7POINT0);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT0_FRONT = AV_CHANNEL_LAYOUT_MASK(7,  AV_CH_LAYOUT_7POINT0_FRONT)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT0_FRONT = AV_CHANNEL_LAYOUT_MASK(7, (ulong)ChannelFlags.Layout_7POINT0Front);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT1 = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_7POINT1)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1 = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.Layout_7POINT1);
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1_TOP_BACK = AV_CHANNEL_LAYOUT_5POINT1POINT2_BACK;
    /// <summary>AV_CHANNEL_LAYOUT_7POINT1_WIDE = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_7POINT1_WIDE)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1_WIDE = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.Layout_7POINT1Wide);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT1_WIDE_BACK = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_7POINT1_WIDE_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1_WIDE_BACK = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.Layout_7POINT1WideBack);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(10, AV_CH_LAYOUT_7POINT1POINT2)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1POINT2 = AV_CHANNEL_LAYOUT_MASK(10, (ulong)ChannelFlags.Layout_7POINT1POINT2);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(12, AV_CH_LAYOUT_7POINT1POINT4_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(12, (ulong)ChannelFlags.Layout_7POINT1POINT4Back);
    /// <summary>AV_CHANNEL_LAYOUT_7POINT2POINT3 = AV_CHANNEL_LAYOUT_MASK(12, AV_CH_LAYOUT_7POINT2POINT3)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_7POINT2POINT3 = AV_CHANNEL_LAYOUT_MASK(12, (ulong)ChannelFlags.Layout_7POINT2POINT3);
    /// <summary>AV_CHANNEL_LAYOUT_9POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(14, AV_CH_LAYOUT_9POINT1POINT4_BACK)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_9POINT1POINT4_BACK = AV_CHANNEL_LAYOUT_MASK(14, (ulong)ChannelFlags.Layout_9POINT1POINT4Back);
    /// <summary>AV_CHANNEL_LAYOUT_9POINT1POINT6 = AV_CHANNEL_LAYOUT_MASK(16, AV_CH_LAYOUT_9POINT1POINT6)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_9POINT1POINT6 = AV_CHANNEL_LAYOUT_MASK(16, (ulong)ChannelFlags.Layout_9POINT1POINT6);
    // public static AV_CHANNEL_LAYOUT_AMBISONIC_FIRST_ORDER = { /* .order */ AV_CHANNEL_ORDER_AMBISONIC, /* .nb_channels */ 4, /* .u.mask */ { 0 }, /* .opaque */ NULL };
    /// <summary>AV_CHANNEL_LAYOUT_BINAURAL = AV_CHANNEL_LAYOUT_MASK(2,  AV_CH_LAYOUT_BINAURAL)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_BINAURAL = AV_CHANNEL_LAYOUT_MASK(2, (ulong)ChannelFlags.LayoutBinaural);
    /// <summary>AV_CHANNEL_LAYOUT_CUBE = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_CUBE)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_CUBE = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.LayoutCube);
    /// <summary>AV_CHANNEL_LAYOUT_HEXADECAGONAL = AV_CHANNEL_LAYOUT_MASK(16, AV_CH_LAYOUT_HEXADECAGONAL)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_HEXADECAGONAL = AV_CHANNEL_LAYOUT_MASK(16, (ulong)ChannelFlags.LayoutHexadecagonal);
    /// <summary>AV_CHANNEL_LAYOUT_HEXAGONAL = AV_CHANNEL_LAYOUT_MASK(6,  AV_CH_LAYOUT_HEXAGONAL)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_HEXAGONAL = AV_CHANNEL_LAYOUT_MASK(6, (ulong)ChannelFlags.LayoutHexagonal);
    // public static AV_CHANNEL_LAYOUT_MASK = (nb, m) { /* .order */ AV_CHANNEL_ORDER_NATIVE, /* .nb_channels */  (nb), /* .u.mask */ { m }, /* .opaque */ NULL };
    /// <summary>AV_CHANNEL_LAYOUT_MONO = AV_CHANNEL_LAYOUT_MASK(1,  AV_CH_LAYOUT_MONO)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_MONO = AV_CHANNEL_LAYOUT_MASK(1, (ulong)ChannelFlags.LayoutMono);
    /// <summary>AV_CHANNEL_LAYOUT_OCTAGONAL = AV_CHANNEL_LAYOUT_MASK(8,  AV_CH_LAYOUT_OCTAGONAL)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_OCTAGONAL = AV_CHANNEL_LAYOUT_MASK(8, (ulong)ChannelFlags.LayoutOctagonal);
    /// <summary>AV_CHANNEL_LAYOUT_QUAD = AV_CHANNEL_LAYOUT_MASK(4,  AV_CH_LAYOUT_QUAD)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_QUAD = AV_CHANNEL_LAYOUT_MASK(4, (ulong)ChannelFlags.LayoutQuad);
    /// <summary>AV_CHANNEL_LAYOUT_RETYPE_FLAG_CANONICAL = (1 &lt;&lt; 1)</summary>
    public const int AV_CHANNEL_LAYOUT_RETYPE_FLAG_CANONICAL = 1 << 1;
    /// <summary>AV_CHANNEL_LAYOUT_RETYPE_FLAG_LOSSLESS = (1 &lt;&lt; 0)</summary>
    public const int AV_CHANNEL_LAYOUT_RETYPE_FLAG_LOSSLESS = 1 << 0;
    /// <summary>AV_CHANNEL_LAYOUT_STEREO = AV_CHANNEL_LAYOUT_MASK(2,  AV_CH_LAYOUT_STEREO)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_STEREO = AV_CHANNEL_LAYOUT_MASK(2, (ulong)ChannelFlags.LayoutStereo);
    /// <summary>AV_CHANNEL_LAYOUT_STEREO_DOWNMIX = AV_CHANNEL_LAYOUT_MASK(2,  AV_CH_LAYOUT_STEREO_DOWNMIX)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_STEREO_DOWNMIX = AV_CHANNEL_LAYOUT_MASK(2, (ulong)ChannelFlags.LayoutStereoDownmix);
    /// <summary>AV_CHANNEL_LAYOUT_SURROUND = AV_CHANNEL_LAYOUT_MASK(3,  AV_CH_LAYOUT_SURROUND)</summary>
    public static readonly AVChannelLayout AV_CHANNEL_LAYOUT_SURROUND = AV_CHANNEL_LAYOUT_MASK(3, (ulong)ChannelFlags.LayoutSurround);
    // public static av_clip = av_clip_c;
    // public static av_clip_int16 = av_clip_int16_c;
    // public static av_clip_int8 = av_clip_int8_c;
    // public static av_clip_intp2 = av_clip_intp2_c;
    // public static av_clip_uint16 = av_clip_uint16_c;
    // public static av_clip_uint8 = av_clip_uint8_c;
    // public static av_clip_uintp2 = av_clip_uintp2_c;
    // public static av_clip64 = av_clip64_c;
    // public static av_clipd = av_clipd_c;
    // public static av_clipf = av_clipf_c;
    // public static av_clipl_int32 = av_clipl_int32_c;
    /// <summary>AV_CODEC_ID_H265 = AV_CODEC_ID_HEVC</summary>
    public static readonly int AV_CODEC_ID_H265 = (int)AVCodecID.Hevc;
    /// <summary>AV_CODEC_ID_H266 = AV_CODEC_ID_VVC</summary>
    public static readonly int AV_CODEC_ID_H266 = (int)AVCodecID.Vvc;
    /// <summary>AV_CODEC_ID_IFF_BYTERUN1 = AV_CODEC_ID_IFF_ILBM</summary>
    public static readonly int AV_CODEC_ID_IFF_BYTERUN1 = (int)AVCodecID.IffIlbm;
    // public static av_cold = __attribute__((cold));
    // public static av_const = __attribute__((const));
    /// <summary>AV_CUDA_USE_CURRENT_CONTEXT = (1 &lt;&lt; 1)</summary>
    public const int AV_CUDA_USE_CURRENT_CONTEXT = 1 << 1;
    /// <summary>AV_CUDA_USE_PRIMARY_CONTEXT = (1 &lt;&lt; 0)</summary>
    public const int AV_CUDA_USE_PRIMARY_CONTEXT = 1 << 0;
    // public static av_err2str = (errnum) av_make_error_string((char[AV_ERROR_MAX_STRING_SIZE]){0}, AV_ERROR_MAX_STRING_SIZE, errnum);
    public const int AV_ERROR_MAX_STRING_SIZE = 64;
    // public static av_extern_inline = inline;
    public const int AV_FOURCC_MAX_STRING_SIZE = 32;
    // public static av_fourcc2str = (fourcc) av_fourcc_make_string((char[AV_FOURCC_MAX_STRING_SIZE]){0}, fourcc);
    public const int AV_FRAME_FILENAME_FLAGS_MULTIPLE = 1;
    // public static AV_GCC_VERSION_AT_LEAST = (x,y) 0;
    // public static AV_GCC_VERSION_AT_MOST = (x,y)  0;
    /// <summary>AV_GET_BUFFER_FLAG_REF = (1 &lt;&lt; 0)</summary>
    public const int AV_GET_BUFFER_FLAG_REF = 1 << 0;
    /// <summary>AV_GET_ENCODE_BUFFER_FLAG_REF = (1 &lt;&lt; 0)</summary>
    public const int AV_GET_ENCODE_BUFFER_FLAG_REF = 1 << 0;
    // public static AV_GLUE = (a, b) a ## b;
    // public static AV_HAS_BUILTIN = (x) __has_builtin(x);
    public const int AV_HAVE_BIGENDIAN = 0;
    public const int AV_HAVE_FAST_UNALIGNED = 1;
    public const int AV_HDR_PLUS_MAX_PAYLOAD_SIZE = 907;
    public const int AV_INPUT_BUFFER_PADDING_SIZE = 64;
    // public static av_int_list_length = (list, term) av_int_list_length_for_size(sizeof(*(list)), list, term);
    // public static AV_IS_INPUT_DEVICE = (category) (((category) == AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT) || ((category) == AV_CLASS_CATEGORY_DEVICE_AUDIO_INPUT) || ((category) == AV_CLASS_CATEGORY_DEVICE_INPUT));
    // public static AV_IS_OUTPUT_DEVICE = (category) (((category) == AV_CLASS_CATEGORY_DEVICE_VIDEO_OUTPUT) || ((category) == AV_CLASS_CATEGORY_DEVICE_AUDIO_OUTPUT) || ((category) == AV_CLASS_CATEGORY_DEVICE_OUTPUT));
    // public static AV_JOIN = (a, b) AV_GLUE(a, b);
    public const int AV_LEVEL_UNKNOWN = -99;
    // public static AV_LOG_C = (x) ((x) << 8);
    // public static av_mod_uintp2 = av_mod_uintp2_c;
    // public static AV_NE = (be, le) (le);
    // public static av_noinline = __declspec(noinline);
    /// <summary>AV_NOPTS_VALUE = ((int64_t)UINT64_C(0x8000000000000000))</summary>
    public static readonly long AV_NOPTS_VALUE = unchecked((long)((ulong)0x8000000000000000));
    // public static av_noreturn = __attribute__((noreturn));
    // public static AV_NOWARN_DEPRECATED = (code) _Pragma("GCC diagnostic push") _Pragma("GCC diagnostic ignored \"-Wdeprecated-declarations\"") code _Pragma("GCC diagnostic pop");
    public const int AV_NUM_DATA_POINTERS = 8;
    /// <summary>AV_OPT_ALLOW_NULL = (1 &lt;&lt; 2)</summary>
    public const int AV_OPT_ALLOW_NULL = 1 << 2;
    /// <summary>AV_OPT_ARRAY_REPLACE = (1 &lt;&lt; 3)</summary>
    public const int AV_OPT_ARRAY_REPLACE = 1 << 3;
    /// <summary>AV_OPT_MULTI_COMPONENT_RANGE = (1 &lt;&lt; 12)</summary>
    public const int AV_OPT_MULTI_COMPONENT_RANGE = 1 << 12;
    // public static av_opt_set_int_list = (obj, name, val, term, flags) (av_int_list_length(val, term) > INT_MAX / sizeof(*(val)) ? AVERROR(EINVAL) : av_opt_set_bin(obj, name, (const uint8_t *)(val), av_int_list_length(val, term) * sizeof(*(val)), flags));
    // public static av_parity = av_parity_c;
    public const int AV_PARSER_PTS_NB = 4;
    // public static AV_PIX_FMT_0BGR32 = AV_PIX_FMT_NE(0BGR, RGB0);
    // public static AV_PIX_FMT_0RGB32 = AV_PIX_FMT_NE(0RGB, BGR0);
    /// <summary>AV_PIX_FMT_AYUV64 = AV_PIX_FMT_NE(AYUV64BE, AYUV64LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_AYUV64 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Ayuv64le : (int)AVPixelFormat.Ayuv64be);
    /// <summary>AV_PIX_FMT_BAYER_BGGR16 = AV_PIX_FMT_NE(BAYER_BGGR16BE,    BAYER_BGGR16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BAYER_BGGR16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.BayerBggr16le : (int)AVPixelFormat.BayerBggr16be);
    /// <summary>AV_PIX_FMT_BAYER_GBRG16 = AV_PIX_FMT_NE(BAYER_GBRG16BE,    BAYER_GBRG16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BAYER_GBRG16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.BayerGbrg16le : (int)AVPixelFormat.BayerGbrg16be);
    /// <summary>AV_PIX_FMT_BAYER_GRBG16 = AV_PIX_FMT_NE(BAYER_GRBG16BE,    BAYER_GRBG16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BAYER_GRBG16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.BayerGrbg16le : (int)AVPixelFormat.BayerGrbg16be);
    /// <summary>AV_PIX_FMT_BAYER_RGGB16 = AV_PIX_FMT_NE(BAYER_RGGB16BE,    BAYER_RGGB16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BAYER_RGGB16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.BayerRggb16le : (int)AVPixelFormat.BayerRggb16be);
    /// <summary>AV_PIX_FMT_BGR32 = AV_PIX_FMT_NE(ABGR, RGBA)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgba : (int)AVPixelFormat.Abgr);
    /// <summary>AV_PIX_FMT_BGR32_1 = AV_PIX_FMT_NE(BGRA, ARGB)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR32_1 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Argb : (int)AVPixelFormat.Bgra);
    /// <summary>AV_PIX_FMT_BGR444 = AV_PIX_FMT_NE(BGR444BE, BGR444LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR444 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgr444le : (int)AVPixelFormat.Bgr444be);
    /// <summary>AV_PIX_FMT_BGR48 = AV_PIX_FMT_NE(BGR48BE,  BGR48LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR48 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgr48le : (int)AVPixelFormat.Bgr48be);
    /// <summary>AV_PIX_FMT_BGR555 = AV_PIX_FMT_NE(BGR555BE, BGR555LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR555 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgr555le : (int)AVPixelFormat.Bgr555be);
    /// <summary>AV_PIX_FMT_BGR565 = AV_PIX_FMT_NE(BGR565BE, BGR565LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGR565 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgr565le : (int)AVPixelFormat.Bgr565be);
    /// <summary>AV_PIX_FMT_BGRA64 = AV_PIX_FMT_NE(BGRA64BE, BGRA64LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_BGRA64 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgra64le : (int)AVPixelFormat.Bgra64be);
    /// <summary>AV_PIX_FMT_GBRAP10 = AV_PIX_FMT_NE(GBRAP10BE,   GBRAP10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAP10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrap10le : (int)AVPixelFormat.Gbrap10be);
    /// <summary>AV_PIX_FMT_GBRAP12 = AV_PIX_FMT_NE(GBRAP12BE,   GBRAP12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAP12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrap12le : (int)AVPixelFormat.Gbrap12be);
    /// <summary>AV_PIX_FMT_GBRAP14 = AV_PIX_FMT_NE(GBRAP14BE,   GBRAP14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAP14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrap14le : (int)AVPixelFormat.Gbrap14be);
    /// <summary>AV_PIX_FMT_GBRAP16 = AV_PIX_FMT_NE(GBRAP16BE,   GBRAP16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAP16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrap16le : (int)AVPixelFormat.Gbrap16be);
    /// <summary>AV_PIX_FMT_GBRAP32 = AV_PIX_FMT_NE(GBRAP32BE,   GBRAP32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAP32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrap32le : (int)AVPixelFormat.Gbrap32be);
    /// <summary>AV_PIX_FMT_GBRAPF16 = AV_PIX_FMT_NE(GBRAPF16BE, GBRAPF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAPF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrapf16le : (int)AVPixelFormat.Gbrapf16be);
    /// <summary>AV_PIX_FMT_GBRAPF32 = AV_PIX_FMT_NE(GBRAPF32BE, GBRAPF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRAPF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrapf32le : (int)AVPixelFormat.Gbrapf32be);
    /// <summary>AV_PIX_FMT_GBRP10 = AV_PIX_FMT_NE(GBRP10BE,    GBRP10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp10le : (int)AVPixelFormat.Gbrp10be);
    /// <summary>AV_PIX_FMT_GBRP10MSB = AV_PIX_FMT_NE(GBRP10MSBBE, GBRP10MSBLE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP10MSB = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp10msble : (int)AVPixelFormat.Gbrp10msbbe);
    /// <summary>AV_PIX_FMT_GBRP12 = AV_PIX_FMT_NE(GBRP12BE,    GBRP12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp12le : (int)AVPixelFormat.Gbrp12be);
    /// <summary>AV_PIX_FMT_GBRP12MSB = AV_PIX_FMT_NE(GBRP12MSBBE, GBRP12MSBLE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP12MSB = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp12msble : (int)AVPixelFormat.Gbrp12msbbe);
    /// <summary>AV_PIX_FMT_GBRP14 = AV_PIX_FMT_NE(GBRP14BE,    GBRP14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp14le : (int)AVPixelFormat.Gbrp14be);
    /// <summary>AV_PIX_FMT_GBRP16 = AV_PIX_FMT_NE(GBRP16BE,    GBRP16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp16le : (int)AVPixelFormat.Gbrp16be);
    /// <summary>AV_PIX_FMT_GBRP9 = AV_PIX_FMT_NE(GBRP9BE ,    GBRP9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRP9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrp9le : (int)AVPixelFormat.Gbrp9be);
    /// <summary>AV_PIX_FMT_GBRPF16 = AV_PIX_FMT_NE(GBRPF16BE,  GBRPF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRPF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrpf16le : (int)AVPixelFormat.Gbrpf16be);
    /// <summary>AV_PIX_FMT_GBRPF32 = AV_PIX_FMT_NE(GBRPF32BE,  GBRPF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GBRPF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gbrpf32le : (int)AVPixelFormat.Gbrpf32be);
    /// <summary>AV_PIX_FMT_GRAY10 = AV_PIX_FMT_NE(GRAY10BE, GRAY10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray10le : (int)AVPixelFormat.Gray10be);
    /// <summary>AV_PIX_FMT_GRAY12 = AV_PIX_FMT_NE(GRAY12BE, GRAY12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray12le : (int)AVPixelFormat.Gray12be);
    /// <summary>AV_PIX_FMT_GRAY14 = AV_PIX_FMT_NE(GRAY14BE, GRAY14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray14le : (int)AVPixelFormat.Gray14be);
    /// <summary>AV_PIX_FMT_GRAY16 = AV_PIX_FMT_NE(GRAY16BE, GRAY16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray16le : (int)AVPixelFormat.Gray16be);
    /// <summary>AV_PIX_FMT_GRAY32 = AV_PIX_FMT_NE(GRAY32BE, GRAY32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray32le : (int)AVPixelFormat.Gray32be);
    /// <summary>AV_PIX_FMT_GRAY9 = AV_PIX_FMT_NE(GRAY9BE,  GRAY9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAY9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Gray9le : (int)AVPixelFormat.Gray9be);
    /// <summary>AV_PIX_FMT_GRAYF16 = AV_PIX_FMT_NE(GRAYF16BE, GRAYF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAYF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Grayf16le : (int)AVPixelFormat.Grayf16be);
    /// <summary>AV_PIX_FMT_GRAYF32 = AV_PIX_FMT_NE(GRAYF32BE, GRAYF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_GRAYF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Grayf32le : (int)AVPixelFormat.Grayf32be);
    // public static AV_PIX_FMT_NE = (be, le) AV_PIX_FMT_##le;
    /// <summary>AV_PIX_FMT_NV20 = AV_PIX_FMT_NE(NV20BE,  NV20LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_NV20 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Nv20le : (int)AVPixelFormat.Nv20be);
    /// <summary>AV_PIX_FMT_P010 = AV_PIX_FMT_NE(P010BE,  P010LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P010 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P010le : (int)AVPixelFormat.P010be);
    /// <summary>AV_PIX_FMT_P012 = AV_PIX_FMT_NE(P012BE,  P012LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P012 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P012le : (int)AVPixelFormat.P012be);
    /// <summary>AV_PIX_FMT_P016 = AV_PIX_FMT_NE(P016BE,  P016LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P016 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P016le : (int)AVPixelFormat.P016be);
    /// <summary>AV_PIX_FMT_P210 = AV_PIX_FMT_NE(P210BE, P210LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P210 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P210le : (int)AVPixelFormat.P210be);
    /// <summary>AV_PIX_FMT_P212 = AV_PIX_FMT_NE(P212BE, P212LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P212 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P212le : (int)AVPixelFormat.P212be);
    /// <summary>AV_PIX_FMT_P216 = AV_PIX_FMT_NE(P216BE, P216LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P216 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P216le : (int)AVPixelFormat.P216be);
    /// <summary>AV_PIX_FMT_P410 = AV_PIX_FMT_NE(P410BE, P410LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P410 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P410le : (int)AVPixelFormat.P410be);
    /// <summary>AV_PIX_FMT_P412 = AV_PIX_FMT_NE(P412BE, P412LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P412 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P412le : (int)AVPixelFormat.P412be);
    /// <summary>AV_PIX_FMT_P416 = AV_PIX_FMT_NE(P416BE, P416LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_P416 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.P416le : (int)AVPixelFormat.P416be);
    /// <summary>AV_PIX_FMT_RGB32 = AV_PIX_FMT_NE(ARGB, BGRA)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Bgra : (int)AVPixelFormat.Argb);
    /// <summary>AV_PIX_FMT_RGB32_1 = AV_PIX_FMT_NE(RGBA, ABGR)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB32_1 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Abgr : (int)AVPixelFormat.Rgba);
    /// <summary>AV_PIX_FMT_RGB444 = AV_PIX_FMT_NE(RGB444BE, RGB444LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB444 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgb444le : (int)AVPixelFormat.Rgb444be);
    /// <summary>AV_PIX_FMT_RGB48 = AV_PIX_FMT_NE(RGB48BE,  RGB48LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB48 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgb48le : (int)AVPixelFormat.Rgb48be);
    /// <summary>AV_PIX_FMT_RGB555 = AV_PIX_FMT_NE(RGB555BE, RGB555LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB555 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgb555le : (int)AVPixelFormat.Rgb555be);
    /// <summary>AV_PIX_FMT_RGB565 = AV_PIX_FMT_NE(RGB565BE, RGB565LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB565 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgb565le : (int)AVPixelFormat.Rgb565be);
    /// <summary>AV_PIX_FMT_RGB96 = AV_PIX_FMT_NE(RGB96BE, RGB96LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGB96 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgb96le : (int)AVPixelFormat.Rgb96be);
    /// <summary>AV_PIX_FMT_RGBA128 = AV_PIX_FMT_NE(RGBA128BE, RGBA128LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBA128 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgba128le : (int)AVPixelFormat.Rgba128be);
    /// <summary>AV_PIX_FMT_RGBA64 = AV_PIX_FMT_NE(RGBA64BE, RGBA64LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBA64 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgba64le : (int)AVPixelFormat.Rgba64be);
    /// <summary>AV_PIX_FMT_RGBAF16 = AV_PIX_FMT_NE(RGBAF16BE, RGBAF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBAF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgbaf16le : (int)AVPixelFormat.Rgbaf16be);
    /// <summary>AV_PIX_FMT_RGBAF32 = AV_PIX_FMT_NE(RGBAF32BE, RGBAF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBAF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgbaf32le : (int)AVPixelFormat.Rgbaf32be);
    /// <summary>AV_PIX_FMT_RGBF16 = AV_PIX_FMT_NE(RGBF16BE, RGBF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgbf16le : (int)AVPixelFormat.Rgbf16be);
    /// <summary>AV_PIX_FMT_RGBF32 = AV_PIX_FMT_NE(RGBF32BE, RGBF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_RGBF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Rgbf32le : (int)AVPixelFormat.Rgbf32be);
    /// <summary>AV_PIX_FMT_V30X = AV_PIX_FMT_NE(V30XBE,  V30XLE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_V30X = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.V30xle : (int)AVPixelFormat.V30xbe);
    /// <summary>AV_PIX_FMT_X2BGR10 = AV_PIX_FMT_NE(X2BGR10BE, X2BGR10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_X2BGR10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.X2bgr10le : (int)AVPixelFormat.X2bgr10be);
    /// <summary>AV_PIX_FMT_X2RGB10 = AV_PIX_FMT_NE(X2RGB10BE, X2RGB10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_X2RGB10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.X2rgb10le : (int)AVPixelFormat.X2rgb10be);
    /// <summary>AV_PIX_FMT_XV30 = AV_PIX_FMT_NE(XV30BE,  XV30LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_XV30 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Xv30le : (int)AVPixelFormat.Xv30be);
    /// <summary>AV_PIX_FMT_XV36 = AV_PIX_FMT_NE(XV36BE,  XV36LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_XV36 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Xv36le : (int)AVPixelFormat.Xv36be);
    /// <summary>AV_PIX_FMT_XV48 = AV_PIX_FMT_NE(XV48BE,  XV48LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_XV48 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Xv48le : (int)AVPixelFormat.Xv48be);
    /// <summary>AV_PIX_FMT_XYZ12 = AV_PIX_FMT_NE(XYZ12BE, XYZ12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_XYZ12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Xyz12le : (int)AVPixelFormat.Xyz12be);
    /// <summary>AV_PIX_FMT_Y210 = AV_PIX_FMT_NE(Y210BE,  Y210LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_Y210 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Y210le : (int)AVPixelFormat.Y210be);
    /// <summary>AV_PIX_FMT_Y212 = AV_PIX_FMT_NE(Y212BE,  Y212LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_Y212 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Y212le : (int)AVPixelFormat.Y212be);
    /// <summary>AV_PIX_FMT_Y216 = AV_PIX_FMT_NE(Y216BE,  Y216LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_Y216 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Y216le : (int)AVPixelFormat.Y216be);
    /// <summary>AV_PIX_FMT_YA16 = AV_PIX_FMT_NE(YA16BE,   YA16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YA16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Ya16le : (int)AVPixelFormat.Ya16be);
    /// <summary>AV_PIX_FMT_YAF16 = AV_PIX_FMT_NE(YAF16BE, YAF16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YAF16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yaf16le : (int)AVPixelFormat.Yaf16be);
    /// <summary>AV_PIX_FMT_YAF32 = AV_PIX_FMT_NE(YAF32BE, YAF32LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YAF32 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yaf32le : (int)AVPixelFormat.Yaf32be);
    /// <summary>AV_PIX_FMT_YUV420P10 = AV_PIX_FMT_NE(YUV420P10BE, YUV420P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV420P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv420p10le : (int)AVPixelFormat.Yuv420p10be);
    /// <summary>AV_PIX_FMT_YUV420P12 = AV_PIX_FMT_NE(YUV420P12BE, YUV420P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV420P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv420p12le : (int)AVPixelFormat.Yuv420p12be);
    /// <summary>AV_PIX_FMT_YUV420P14 = AV_PIX_FMT_NE(YUV420P14BE, YUV420P14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV420P14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv420p14le : (int)AVPixelFormat.Yuv420p14be);
    /// <summary>AV_PIX_FMT_YUV420P16 = AV_PIX_FMT_NE(YUV420P16BE, YUV420P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV420P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv420p16le : (int)AVPixelFormat.Yuv420p16be);
    /// <summary>AV_PIX_FMT_YUV420P9 = AV_PIX_FMT_NE(YUV420P9BE , YUV420P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV420P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv420p9le : (int)AVPixelFormat.Yuv420p9be);
    /// <summary>AV_PIX_FMT_YUV422P10 = AV_PIX_FMT_NE(YUV422P10BE, YUV422P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV422P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv422p10le : (int)AVPixelFormat.Yuv422p10be);
    /// <summary>AV_PIX_FMT_YUV422P12 = AV_PIX_FMT_NE(YUV422P12BE, YUV422P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV422P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv422p12le : (int)AVPixelFormat.Yuv422p12be);
    /// <summary>AV_PIX_FMT_YUV422P14 = AV_PIX_FMT_NE(YUV422P14BE, YUV422P14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV422P14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv422p14le : (int)AVPixelFormat.Yuv422p14be);
    /// <summary>AV_PIX_FMT_YUV422P16 = AV_PIX_FMT_NE(YUV422P16BE, YUV422P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV422P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv422p16le : (int)AVPixelFormat.Yuv422p16be);
    /// <summary>AV_PIX_FMT_YUV422P9 = AV_PIX_FMT_NE(YUV422P9BE , YUV422P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV422P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv422p9le : (int)AVPixelFormat.Yuv422p9be);
    /// <summary>AV_PIX_FMT_YUV440P10 = AV_PIX_FMT_NE(YUV440P10BE, YUV440P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV440P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv440p10le : (int)AVPixelFormat.Yuv440p10be);
    /// <summary>AV_PIX_FMT_YUV440P12 = AV_PIX_FMT_NE(YUV440P12BE, YUV440P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV440P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv440p12le : (int)AVPixelFormat.Yuv440p12be);
    /// <summary>AV_PIX_FMT_YUV444P10 = AV_PIX_FMT_NE(YUV444P10BE, YUV444P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p10le : (int)AVPixelFormat.Yuv444p10be);
    /// <summary>AV_PIX_FMT_YUV444P10MSB = AV_PIX_FMT_NE(YUV444P10MSBBE, YUV444P10MSBLE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P10MSB = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p10msble : (int)AVPixelFormat.Yuv444p10msbbe);
    /// <summary>AV_PIX_FMT_YUV444P12 = AV_PIX_FMT_NE(YUV444P12BE, YUV444P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p12le : (int)AVPixelFormat.Yuv444p12be);
    /// <summary>AV_PIX_FMT_YUV444P12MSB = AV_PIX_FMT_NE(YUV444P12MSBBE, YUV444P12MSBLE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P12MSB = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p12msble : (int)AVPixelFormat.Yuv444p12msbbe);
    /// <summary>AV_PIX_FMT_YUV444P14 = AV_PIX_FMT_NE(YUV444P14BE, YUV444P14LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P14 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p14le : (int)AVPixelFormat.Yuv444p14be);
    /// <summary>AV_PIX_FMT_YUV444P16 = AV_PIX_FMT_NE(YUV444P16BE, YUV444P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p16le : (int)AVPixelFormat.Yuv444p16be);
    /// <summary>AV_PIX_FMT_YUV444P9 = AV_PIX_FMT_NE(YUV444P9BE , YUV444P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUV444P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuv444p9le : (int)AVPixelFormat.Yuv444p9be);
    /// <summary>AV_PIX_FMT_YUVA420P10 = AV_PIX_FMT_NE(YUVA420P10BE, YUVA420P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA420P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva420p10le : (int)AVPixelFormat.Yuva420p10be);
    /// <summary>AV_PIX_FMT_YUVA420P16 = AV_PIX_FMT_NE(YUVA420P16BE, YUVA420P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA420P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva420p16le : (int)AVPixelFormat.Yuva420p16be);
    /// <summary>AV_PIX_FMT_YUVA420P9 = AV_PIX_FMT_NE(YUVA420P9BE , YUVA420P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA420P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva420p9le : (int)AVPixelFormat.Yuva420p9be);
    /// <summary>AV_PIX_FMT_YUVA422P10 = AV_PIX_FMT_NE(YUVA422P10BE, YUVA422P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA422P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva422p10le : (int)AVPixelFormat.Yuva422p10be);
    /// <summary>AV_PIX_FMT_YUVA422P12 = AV_PIX_FMT_NE(YUVA422P12BE, YUVA422P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA422P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva422p12le : (int)AVPixelFormat.Yuva422p12be);
    /// <summary>AV_PIX_FMT_YUVA422P16 = AV_PIX_FMT_NE(YUVA422P16BE, YUVA422P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA422P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva422p16le : (int)AVPixelFormat.Yuva422p16be);
    /// <summary>AV_PIX_FMT_YUVA422P9 = AV_PIX_FMT_NE(YUVA422P9BE , YUVA422P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA422P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva422p9le : (int)AVPixelFormat.Yuva422p9be);
    /// <summary>AV_PIX_FMT_YUVA444P10 = AV_PIX_FMT_NE(YUVA444P10BE, YUVA444P10LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA444P10 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva444p10le : (int)AVPixelFormat.Yuva444p10be);
    /// <summary>AV_PIX_FMT_YUVA444P12 = AV_PIX_FMT_NE(YUVA444P12BE, YUVA444P12LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA444P12 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva444p12le : (int)AVPixelFormat.Yuva444p12be);
    /// <summary>AV_PIX_FMT_YUVA444P16 = AV_PIX_FMT_NE(YUVA444P16BE, YUVA444P16LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA444P16 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva444p16le : (int)AVPixelFormat.Yuva444p16be);
    /// <summary>AV_PIX_FMT_YUVA444P9 = AV_PIX_FMT_NE(YUVA444P9BE , YUVA444P9LE)</summary>
    public static readonly AVPixelFormat AV_PIX_FMT_YUVA444P9 = (AVPixelFormat)(BitConverter.IsLittleEndian ? (int)AVPixelFormat.Yuva444p9le : (int)AVPixelFormat.Yuva444p9be);
    // public static av_popcount = av_popcount_c;
    // public static av_popcount64 = av_popcount64_c;
    // public static AV_PRAGMA = (s) _Pragma(#s);
    // public static av_printf_format = (fmtpos, attrpos) __attribute__((__format__(__printf__, fmtpos, attrpos)));
    public const int AV_PROFILE_AAC_ELD = 38;
    public const int AV_PROFILE_AAC_HE = 4;
    public const int AV_PROFILE_AAC_HE_V2 = 28;
    public const int AV_PROFILE_AAC_LD = 22;
    public const int AV_PROFILE_AAC_LOW = 1;
    public const int AV_PROFILE_AAC_LTP = 3;
    public const int AV_PROFILE_AAC_MAIN = 0;
    public const int AV_PROFILE_AAC_SSR = 2;
    public const int AV_PROFILE_AAC_USAC = 41;
    public const int AV_PROFILE_APV_400_10 = 99;
    public const int AV_PROFILE_APV_422_10 = 33;
    public const int AV_PROFILE_APV_422_12 = 44;
    public const int AV_PROFILE_APV_444_10 = 55;
    public const int AV_PROFILE_APV_444_12 = 66;
    public const int AV_PROFILE_APV_4444_10 = 77;
    public const int AV_PROFILE_APV_4444_12 = 88;
    public const int AV_PROFILE_ARIB_PROFILE_A = 0;
    public const int AV_PROFILE_ARIB_PROFILE_C = 1;
    public const int AV_PROFILE_AV1_HIGH = 1;
    public const int AV_PROFILE_AV1_MAIN = 0;
    public const int AV_PROFILE_AV1_PROFESSIONAL = 2;
    public const int AV_PROFILE_DNXHD = 0;
    public const int AV_PROFILE_DNXHR_444 = 5;
    public const int AV_PROFILE_DNXHR_HQ = 3;
    public const int AV_PROFILE_DNXHR_HQX = 4;
    public const int AV_PROFILE_DNXHR_LB = 1;
    public const int AV_PROFILE_DNXHR_SQ = 2;
    public const int AV_PROFILE_DTS = 20;
    public const int AV_PROFILE_DTS_96_24 = 40;
    public const int AV_PROFILE_DTS_ES = 30;
    public const int AV_PROFILE_DTS_EXPRESS = 70;
    public const int AV_PROFILE_DTS_HD_HRA = 50;
    public const int AV_PROFILE_DTS_HD_MA = 60;
    public const int AV_PROFILE_DTS_HD_MA_X = 61;
    public const int AV_PROFILE_DTS_HD_MA_X_IMAX = 62;
    public const int AV_PROFILE_EAC3_DDP_ATMOS = 30;
    public const int AV_PROFILE_EVC_BASELINE = 0;
    public const int AV_PROFILE_EVC_MAIN = 1;
    public const int AV_PROFILE_H264_BASELINE = 66;
    public const int AV_PROFILE_H264_CAVLC_444 = 44;
    /// <summary>AV_PROFILE_H264_CONSTRAINED = (1&lt;&lt;9)</summary>
    public const int AV_PROFILE_H264_CONSTRAINED = 1 << 9;
    /// <summary>AV_PROFILE_H264_CONSTRAINED_BASELINE = (66|AV_PROFILE_H264_CONSTRAINED)</summary>
    public const int AV_PROFILE_H264_CONSTRAINED_BASELINE = 66 | AV_PROFILE_H264_CONSTRAINED;
    public const int AV_PROFILE_H264_EXTENDED = 88;
    public const int AV_PROFILE_H264_HIGH = 100;
    public const int AV_PROFILE_H264_HIGH_10 = 110;
    /// <summary>AV_PROFILE_H264_HIGH_10_INTRA = (110|AV_PROFILE_H264_INTRA)</summary>
    public const int AV_PROFILE_H264_HIGH_10_INTRA = 110 | AV_PROFILE_H264_INTRA;
    public const int AV_PROFILE_H264_HIGH_422 = 122;
    /// <summary>AV_PROFILE_H264_HIGH_422_INTRA = (122|AV_PROFILE_H264_INTRA)</summary>
    public const int AV_PROFILE_H264_HIGH_422_INTRA = 122 | AV_PROFILE_H264_INTRA;
    public const int AV_PROFILE_H264_HIGH_444 = 144;
    /// <summary>AV_PROFILE_H264_HIGH_444_INTRA = (244|AV_PROFILE_H264_INTRA)</summary>
    public const int AV_PROFILE_H264_HIGH_444_INTRA = 244 | AV_PROFILE_H264_INTRA;
    public const int AV_PROFILE_H264_HIGH_444_PREDICTIVE = 244;
    /// <summary>AV_PROFILE_H264_INTRA = (1&lt;&lt;11)</summary>
    public const int AV_PROFILE_H264_INTRA = 1 << 11;
    public const int AV_PROFILE_H264_MAIN = 77;
    public const int AV_PROFILE_H264_MULTIVIEW_HIGH = 118;
    public const int AV_PROFILE_H264_STEREO_HIGH = 128;
    public const int AV_PROFILE_HEVC_MAIN = 1;
    public const int AV_PROFILE_HEVC_MAIN_10 = 2;
    public const int AV_PROFILE_HEVC_MAIN_STILL_PICTURE = 3;
    public const int AV_PROFILE_HEVC_MULTIVIEW_MAIN = 6;
    public const int AV_PROFILE_HEVC_REXT = 4;
    public const int AV_PROFILE_HEVC_SCC = 9;
    public const int AV_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION = 32768;
    public const int AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0 = 1;
    public const int AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1 = 2;
    public const int AV_PROFILE_JPEG2000_DCINEMA_2K = 3;
    public const int AV_PROFILE_JPEG2000_DCINEMA_4K = 4;
    public const int AV_PROFILE_KLVA_ASYNC = 1;
    public const int AV_PROFILE_KLVA_SYNC = 0;
    public const uint AV_PROFILE_MJPEG_HUFFMAN_BASELINE_DCT = 0xc0;
    public const uint AV_PROFILE_MJPEG_HUFFMAN_EXTENDED_SEQUENTIAL_DCT = 0xc1;
    public const uint AV_PROFILE_MJPEG_HUFFMAN_LOSSLESS = 0xc3;
    public const uint AV_PROFILE_MJPEG_HUFFMAN_PROGRESSIVE_DCT = 0xc2;
    public const uint AV_PROFILE_MJPEG_JPEG_LS = 0xf7;
    public const int AV_PROFILE_MPEG2_422 = 0;
    public const int AV_PROFILE_MPEG2_AAC_HE = 131;
    public const int AV_PROFILE_MPEG2_AAC_LOW = 128;
    public const int AV_PROFILE_MPEG2_HIGH = 1;
    public const int AV_PROFILE_MPEG2_MAIN = 4;
    public const int AV_PROFILE_MPEG2_SIMPLE = 5;
    public const int AV_PROFILE_MPEG2_SNR_SCALABLE = 3;
    public const int AV_PROFILE_MPEG2_SS = 2;
    public const int AV_PROFILE_MPEG4_ADVANCED_CODING = 11;
    public const int AV_PROFILE_MPEG4_ADVANCED_CORE = 12;
    public const int AV_PROFILE_MPEG4_ADVANCED_REAL_TIME = 9;
    public const int AV_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE = 13;
    public const int AV_PROFILE_MPEG4_ADVANCED_SIMPLE = 15;
    public const int AV_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE = 7;
    public const int AV_PROFILE_MPEG4_CORE = 2;
    public const int AV_PROFILE_MPEG4_CORE_SCALABLE = 10;
    public const int AV_PROFILE_MPEG4_HYBRID = 8;
    public const int AV_PROFILE_MPEG4_MAIN = 3;
    public const int AV_PROFILE_MPEG4_N_BIT = 4;
    public const int AV_PROFILE_MPEG4_SCALABLE_TEXTURE = 5;
    public const int AV_PROFILE_MPEG4_SIMPLE = 0;
    public const int AV_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION = 6;
    public const int AV_PROFILE_MPEG4_SIMPLE_SCALABLE = 1;
    public const int AV_PROFILE_MPEG4_SIMPLE_STUDIO = 14;
    public const int AV_PROFILE_PRORES_4444 = 4;
    public const int AV_PROFILE_PRORES_HQ = 3;
    public const int AV_PROFILE_PRORES_LT = 1;
    public const int AV_PROFILE_PRORES_PROXY = 0;
    public const int AV_PROFILE_PRORES_RAW = 0;
    public const int AV_PROFILE_PRORES_RAW_HQ = 1;
    public const int AV_PROFILE_PRORES_STANDARD = 2;
    public const int AV_PROFILE_PRORES_XQ = 5;
    public const int AV_PROFILE_RESERVED = -100;
    public const int AV_PROFILE_SBC_MSBC = 1;
    public const int AV_PROFILE_TRUEHD_ATMOS = 30;
    public const int AV_PROFILE_UNKNOWN = -99;
    public const int AV_PROFILE_VC1_ADVANCED = 3;
    public const int AV_PROFILE_VC1_COMPLEX = 2;
    public const int AV_PROFILE_VC1_MAIN = 1;
    public const int AV_PROFILE_VC1_SIMPLE = 0;
    public const int AV_PROFILE_VP9_0 = 0;
    public const int AV_PROFILE_VP9_1 = 1;
    public const int AV_PROFILE_VP9_2 = 2;
    public const int AV_PROFILE_VP9_3 = 3;
    public const int AV_PROFILE_VVC_MAIN_10 = 1;
    public const int AV_PROFILE_VVC_MAIN_10_444 = 33;
    public const int AV_PROGRAM_RUNNING = 1;
    public const int AV_PTS_WRAP_ADD_OFFSET = 1;
    public const int AV_PTS_WRAP_IGNORE = 0;
    public const int AV_PTS_WRAP_SUB_OFFSET = -1;
    // public static av_pure = __attribute__((pure));
    // public static av_sat_add32 = av_sat_add32_c;
    // public static av_sat_add64 = av_sat_add64_c;
    // public static av_sat_dadd32 = av_sat_dadd32_c;
    // public static av_sat_dsub32 = av_sat_dsub32_c;
    // public static av_sat_sub32 = av_sat_sub32_c;
    // public static av_sat_sub64 = av_sat_sub64_c;
    // public static av_scanf_format = (fmtpos, attrpos) __attribute__((__format__(__scanf__, fmtpos, attrpos)));
    // public static AV_STRINGIFY = (s)         AV_TOSTRING(s);
    public const uint AV_SUBTITLE_FLAG_FORCED = 0x00000001;
    public const int AV_TIME_BASE = 1000000;
    // public static AV_TIME_BASE_Q = (AVRational){1, AV_TIME_BASE};
    public const int AV_TIMECODE_STR_SIZE = 23;
    // public static AV_TOSTRING = (s) #s;
    // public static av_uninit = (x) x=x;
    // public static av_unused = __attribute__((unused));
    // public static av_used = __attribute__((used));
    // public static AV_VERSION = (a, b, c) AV_VERSION_DOT(a, b, c);
    // public static AV_VERSION_DOT = (a, b, c) a ##.## b ##.## c;
    // public static AV_VERSION_INT = (a, b, c) ((a)<<16 | (b)<<8 | (c));
    // public static AV_VERSION_MAJOR = (a) ((a) >> 16);
    // public static AV_VERSION_MICRO = (a) ((a) & 0xFF);
    // public static AV_VERSION_MINOR = (a) (((a) & 0x00FF00) >> 8);
    public const int AV_VIDEO_MAX_PLANES = 4;
    // public static av_zero_extend = av_zero_extend_c;
    // public static AVERROR = (e) (-(e));
    /// <summary>AVERROR_BSF_NOT_FOUND = FFERRTAG(0xF8,&apos;B&apos;,&apos;S&apos;,&apos;F&apos;)</summary>
    public static readonly int AVERROR_BSF_NOT_FOUND = FFERRTAG(0xF8, 'B', 'S', 'F');
    /// <summary>AVERROR_BUFFER_TOO_SMALL = FFERRTAG( &apos;B&apos;,&apos;U&apos;,&apos;F&apos;,&apos;S&apos;)</summary>
    public static readonly int AVERROR_BUFFER_TOO_SMALL = FFERRTAG('B', 'U', 'F', 'S');
    /// <summary>AVERROR_BUG = FFERRTAG( &apos;B&apos;,&apos;U&apos;,&apos;G&apos;,&apos;!&apos;)</summary>
    public static readonly int AVERROR_BUG = FFERRTAG('B', 'U', 'G', '!');
    /// <summary>AVERROR_BUG2 = FFERRTAG( &apos;B&apos;,&apos;U&apos;,&apos;G&apos;,&apos; &apos;)</summary>
    public static readonly int AVERROR_BUG2 = FFERRTAG('B', 'U', 'G', ' ');
    /// <summary>AVERROR_DECODER_NOT_FOUND = FFERRTAG(0xF8,&apos;D&apos;,&apos;E&apos;,&apos;C&apos;)</summary>
    public static readonly int AVERROR_DECODER_NOT_FOUND = FFERRTAG(0xF8, 'D', 'E', 'C');
    /// <summary>AVERROR_DEMUXER_NOT_FOUND = FFERRTAG(0xF8,&apos;D&apos;,&apos;E&apos;,&apos;M&apos;)</summary>
    public static readonly int AVERROR_DEMUXER_NOT_FOUND = FFERRTAG(0xF8, 'D', 'E', 'M');
    /// <summary>AVERROR_ENCODER_NOT_FOUND = FFERRTAG(0xF8,&apos;E&apos;,&apos;N&apos;,&apos;C&apos;)</summary>
    public static readonly int AVERROR_ENCODER_NOT_FOUND = FFERRTAG(0xF8, 'E', 'N', 'C');
    /// <summary>AVERROR_EOF = FFERRTAG( &apos;E&apos;,&apos;O&apos;,&apos;F&apos;,&apos; &apos;)</summary>
    public static readonly int AVERROR_EOF = FFERRTAG('E', 'O', 'F', ' ');
    /// <summary>AVERROR_EXIT = FFERRTAG( &apos;E&apos;,&apos;X&apos;,&apos;I&apos;,&apos;T&apos;)</summary>
    public static readonly int AVERROR_EXIT = FFERRTAG('E', 'X', 'I', 'T');
    /// <summary>AVERROR_EXPERIMENTAL = (-0x2bb2afa8)</summary>
    public const int AVERROR_EXPERIMENTAL = -0x2bb2afa8;
    /// <summary>AVERROR_EXTERNAL = FFERRTAG( &apos;E&apos;,&apos;X&apos;,&apos;T&apos;,&apos; &apos;)</summary>
    public static readonly int AVERROR_EXTERNAL = FFERRTAG('E', 'X', 'T', ' ');
    /// <summary>AVERROR_FILTER_NOT_FOUND = FFERRTAG(0xF8,&apos;F&apos;,&apos;I&apos;,&apos;L&apos;)</summary>
    public static readonly int AVERROR_FILTER_NOT_FOUND = FFERRTAG(0xF8, 'F', 'I', 'L');
    /// <summary>AVERROR_HTTP_BAD_REQUEST = FFERRTAG(0xF8,&apos;4&apos;,&apos;0&apos;,&apos;0&apos;)</summary>
    public static readonly int AVERROR_HTTP_BAD_REQUEST = FFERRTAG(0xF8, '4', '0', '0');
    /// <summary>AVERROR_HTTP_FORBIDDEN = FFERRTAG(0xF8,&apos;4&apos;,&apos;0&apos;,&apos;3&apos;)</summary>
    public static readonly int AVERROR_HTTP_FORBIDDEN = FFERRTAG(0xF8, '4', '0', '3');
    /// <summary>AVERROR_HTTP_NOT_FOUND = FFERRTAG(0xF8,&apos;4&apos;,&apos;0&apos;,&apos;4&apos;)</summary>
    public static readonly int AVERROR_HTTP_NOT_FOUND = FFERRTAG(0xF8, '4', '0', '4');
    /// <summary>AVERROR_HTTP_OTHER_4XX = FFERRTAG(0xF8,&apos;4&apos;,&apos;X&apos;,&apos;X&apos;)</summary>
    public static readonly int AVERROR_HTTP_OTHER_4XX = FFERRTAG(0xF8, '4', 'X', 'X');
    /// <summary>AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0xF8,&apos;5&apos;,&apos;X&apos;,&apos;X&apos;)</summary>
    public static readonly int AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0xF8, '5', 'X', 'X');
    /// <summary>AVERROR_HTTP_TOO_MANY_REQUESTS = FFERRTAG(0xF8,&apos;4&apos;,&apos;2&apos;,&apos;9&apos;)</summary>
    public static readonly int AVERROR_HTTP_TOO_MANY_REQUESTS = FFERRTAG(0xF8, '4', '2', '9');
    /// <summary>AVERROR_HTTP_UNAUTHORIZED = FFERRTAG(0xF8,&apos;4&apos;,&apos;0&apos;,&apos;1&apos;)</summary>
    public static readonly int AVERROR_HTTP_UNAUTHORIZED = FFERRTAG(0xF8, '4', '0', '1');
    /// <summary>AVERROR_INPUT_CHANGED = (-0x636e6701)</summary>
    public const int AVERROR_INPUT_CHANGED = -0x636e6701;
    /// <summary>AVERROR_INVALIDDATA = FFERRTAG( &apos;I&apos;,&apos;N&apos;,&apos;D&apos;,&apos;A&apos;)</summary>
    public static readonly int AVERROR_INVALIDDATA = FFERRTAG('I', 'N', 'D', 'A');
    /// <summary>AVERROR_MUXER_NOT_FOUND = FFERRTAG(0xF8,&apos;M&apos;,&apos;U&apos;,&apos;X&apos;)</summary>
    public static readonly int AVERROR_MUXER_NOT_FOUND = FFERRTAG(0xF8, 'M', 'U', 'X');
    /// <summary>AVERROR_OPTION_NOT_FOUND = FFERRTAG(0xF8,&apos;O&apos;,&apos;P&apos;,&apos;T&apos;)</summary>
    public static readonly int AVERROR_OPTION_NOT_FOUND = FFERRTAG(0xF8, 'O', 'P', 'T');
    /// <summary>AVERROR_OUTPUT_CHANGED = (-0x636e6702)</summary>
    public const int AVERROR_OUTPUT_CHANGED = -0x636e6702;
    /// <summary>AVERROR_PATCHWELCOME = FFERRTAG( &apos;P&apos;,&apos;A&apos;,&apos;W&apos;,&apos;E&apos;)</summary>
    public static readonly int AVERROR_PATCHWELCOME = FFERRTAG('P', 'A', 'W', 'E');
    /// <summary>AVERROR_PROTOCOL_NOT_FOUND = FFERRTAG(0xF8,&apos;P&apos;,&apos;R&apos;,&apos;O&apos;)</summary>
    public static readonly int AVERROR_PROTOCOL_NOT_FOUND = FFERRTAG(0xF8, 'P', 'R', 'O');
    /// <summary>AVERROR_STREAM_NOT_FOUND = FFERRTAG(0xF8,&apos;S&apos;,&apos;T&apos;,&apos;R&apos;)</summary>
    public static readonly int AVERROR_STREAM_NOT_FOUND = FFERRTAG(0xF8, 'S', 'T', 'R');
    /// <summary>AVERROR_UNKNOWN = FFERRTAG( &apos;U&apos;,&apos;N&apos;,&apos;K&apos;,&apos;N&apos;)</summary>
    public static readonly int AVERROR_UNKNOWN = FFERRTAG('U', 'N', 'K', 'N');
    // public static AVFILTER_DEFINE_CLASS = (fname) AVFILTER_DEFINE_CLASS_EXT(fname, #fname, fname##_options);
    // public static AVFILTER_DEFINE_CLASS_EXT = (name, desc, options) static const AVClass name##_class = {       .class_name = desc,                     .item_name  = av_default_item_name,     .option     = options,                  .version    = LIBAVUTIL_VERSION_INT,    .category   = AV_CLASS_CATEGORY_FILTER, };
    /// <summary>AVFILTER_FLAG_SUPPORT_TIMELINE = (AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL)</summary>
    public const int AVFILTER_FLAG_SUPPORT_TIMELINE = (int)FilterFlags.SupportTimelineGeneric | (int)FilterFlags.SupportTimelineInternal;
    // public static avio_print = (s, ...) avio_print_string_array(s, (const char*[]){__VA_ARGS__, NULL});
    // public static AVOID_NEGATIVE_TS_ENABLED = (status) ((status) >= 0);
    // public static AVPACKET_IS_EMPTY = (pkt) (!(pkt)->data && !(pkt)->side_data_elems);
    public const int AVPALETTE_COUNT = 256;
    public const int AVPALETTE_SIZE = 1024;
    public const int AVPROBE_PADDING_SIZE = 32;
    public const int AVPROBE_SCORE_EXTENSION = 50;
    public const int AVPROBE_SCORE_MAX = 100;
    public const int AVPROBE_SCORE_MIME_BONUS = 30;
    /// <summary>AVPROBE_SCORE_RETRY = (AVPROBE_SCORE_MAX/4)</summary>
    public const int AVPROBE_SCORE_RETRY = AVPROBE_SCORE_MAX / 4;
    /// <summary>AVPROBE_SCORE_STREAM_RETRY = (AVPROBE_SCORE_MAX/4-1)</summary>
    public const int AVPROBE_SCORE_STREAM_RETRY = AVPROBE_SCORE_MAX / 4 - 1;
    // public static AVUNERROR = (e) (-(e));
    // public static D2TS = (d)      (isnan(d) ? AV_NOPTS_VALUE : (int64_t)(d));
    // public static dynarray_add = (tab, nb_ptr, elem)do {__typeof__(tab) _tab = (tab);__typeof__(elem) _elem = (elem);(void)sizeof(**_tab == _elem); /* check that types are compatible */av_dynarray_add(_tab, nb_ptr, _elem);} while(0);
    /// <summary>FF_API_ALSA_CHANNELS = (LIBAVDEVICE_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_ALSA_CHANNELS = LIBAVDEVICE_VERSION_MAJOR < 63;
    /// <summary>FF_API_BUFFERSINK_OPTS = (LIBAVFILTER_VERSION_MAJOR &lt; 12)</summary>
    public const bool FF_API_BUFFERSINK_OPTS = LIBAVFILTER_VERSION_MAJOR < 12;
    /// <summary>FF_API_CODEC_PROPS = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_CODEC_PROPS = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_COMPUTE_PKT_FIELDS2 = (LIBAVFORMAT_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_COMPUTE_PKT_FIELDS2 = LIBAVFORMAT_VERSION_MAJOR < 63;
    /// <summary>FF_API_CONTEXT_PUBLIC = (LIBAVFILTER_VERSION_MAJOR &lt; 12)</summary>
    public const bool FF_API_CONTEXT_PUBLIC = LIBAVFILTER_VERSION_MAJOR < 12;
    /// <summary>FF_API_EXR_GAMMA = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_EXR_GAMMA = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_INIT_PACKET = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_INIT_PACKET = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_INTERNAL_TIMING = (LIBAVFORMAT_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_INTERNAL_TIMING = LIBAVFORMAT_VERSION_MAJOR < 63;
    /// <summary>FF_API_MOD_UINTP2 = (LIBAVUTIL_VERSION_MAJOR &lt; 61)</summary>
    public const bool FF_API_MOD_UINTP2 = LIBAVUTIL_VERSION_MAJOR < 61;
    /// <summary>FF_API_NO_DEFAULT_TLS_VERIFY = (LIBAVFORMAT_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_NO_DEFAULT_TLS_VERIFY = LIBAVFORMAT_VERSION_MAJOR < 63;
    /// <summary>FF_API_NVDEC_OLD_PIX_FMTS = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_NVDEC_OLD_PIX_FMTS = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_OLD_EXIF = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_OLD_EXIF = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_OPT_INT_LIST = (LIBAVUTIL_VERSION_MAJOR &lt; 61)</summary>
    public const bool FF_API_OPT_INT_LIST = LIBAVUTIL_VERSION_MAJOR < 61;
    /// <summary>FF_API_OPT_PTR = (LIBAVUTIL_VERSION_MAJOR &lt; 61)</summary>
    public const bool FF_API_OPT_PTR = LIBAVUTIL_VERSION_MAJOR < 61;
    public const int FF_API_R_FRAME_RATE = 1;
    /// <summary>FF_API_RISCV_FD_ZBA = (LIBAVUTIL_VERSION_MAJOR &lt; 61)</summary>
    public const bool FF_API_RISCV_FD_ZBA = LIBAVUTIL_VERSION_MAJOR < 61;
    /// <summary>FF_API_V408_CODECID = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_API_V408_CODECID = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_API_VULKAN_FIXED_QUEUES = (LIBAVUTIL_VERSION_MAJOR &lt; 61)</summary>
    public const bool FF_API_VULKAN_FIXED_QUEUES = LIBAVUTIL_VERSION_MAJOR < 61;
    // public static FF_ARRAY_ELEMS = (a) (sizeof(a) / sizeof((a)[0]));
    // public static FF_CEIL_RSHIFT = AV_CEIL_RSHIFT;
    /// <summary>FF_CODEC_OMX = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_CODEC_OMX = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_CODEC_SONIC_DEC = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_CODEC_SONIC_DEC = LIBAVCODEC_VERSION_MAJOR < 63;
    /// <summary>FF_CODEC_SONIC_ENC = (LIBAVCODEC_VERSION_MAJOR &lt; 63)</summary>
    public const bool FF_CODEC_SONIC_ENC = LIBAVCODEC_VERSION_MAJOR < 63;
    public const int FF_COMPRESSION_DEFAULT = -1;
    public const uint FF_FDEBUG_TS = 0x0001;
    /// <summary>FF_FILTER_FLAG_HWFRAME_AWARE = (1 &lt;&lt; 0)</summary>
    public const int FF_FILTER_FLAG_HWFRAME_AWARE = 1 << 0;
    // public static FF_FILTER_FORWARD_STATUS = (inlink, outlink) do { int status; int64_t pts; if (ff_inlink_acknowledge_status(inlink, &status, &pts)) { ff_outlink_set_status(outlink, status, pts); return 0; } } while (0);
    // public static FF_FILTER_FORWARD_STATUS_ALL = (inlink, filter) do { int status; int64_t pts; if (ff_inlink_acknowledge_status(inlink, &status, &pts)) { unsigned i; for (i = 0; i < filter->nb_outputs; i++) ff_outlink_set_status(filter->outputs[i], status, pts); return 0; } } while (0);
    // public static FF_FILTER_FORWARD_STATUS_BACK = (outlink, inlink) do { int ret = ff_outlink_get_status(outlink); if (ret) { ff_inlink_set_status(inlink, ret); return 0; } } while (0);
    // public static FF_FILTER_FORWARD_STATUS_BACK_ALL = (outlink, filter) do { int ret = ff_outlink_get_status(outlink); if (ret) { unsigned i; for (i = 0; i < filter->nb_inputs; i++) ff_inlink_set_status(filter->inputs[i], ret); return 0; } } while (0);
    // public static FF_FILTER_FORWARD_WANTED = (outlink, inlink) do { if (ff_outlink_frame_wanted(outlink)) { ff_inlink_request_frame(inlink); return 0; } } while (0);
    // public static FF_FILTER_FORWARD_WANTED_ANY = (filter, inlink) do { for (unsigned i = 0; i < filter->nb_outputs; i++) { if (ff_outlink_frame_wanted(filter->outputs[i])) { ff_inlink_request_frame(inlink); return 0; } } } while (0);
    // public static FF_INLINK_IDX = (link)  ((int)((link)->dstpad - (link)->dst->input_pads));
    /// <summary>FF_LAMBDA_MAX = (256*128-1)</summary>
    public const int FF_LAMBDA_MAX = 256 * 128 - 1;
    /// <summary>FF_LAMBDA_SCALE = (1&lt;&lt;FF_LAMBDA_SHIFT)</summary>
    public const int FF_LAMBDA_SCALE = 1 << FF_LAMBDA_SHIFT;
    public const int FF_LAMBDA_SHIFT = 7;
    public const uint FF_LOSS_ALPHA = 0x0008;
    public const uint FF_LOSS_CHROMA = 0x0020;
    public const uint FF_LOSS_COLORQUANT = 0x0010;
    public const uint FF_LOSS_COLORSPACE = 0x0004;
    public const uint FF_LOSS_DEPTH = 0x0002;
    public const uint FF_LOSS_EXCESS_DEPTH = 0x0080;
    public const uint FF_LOSS_EXCESS_RESOLUTION = 0x0040;
    public const uint FF_LOSS_RESOLUTION = 0x0001;
    // public static FF_OUTLINK_IDX = (link) ((int)((link)->srcpad - (link)->src->output_pads));
    public const int FF_QP2LAMBDA = 118;
    public const int FF_QUALITY_SCALE = FF_LAMBDA_SCALE;
    // public static FFABS = (a) ((a) >= 0 ? (a) : (-(a)));
    // public static FFABS64U = (a) ((a) <= 0 ? -(uint64_t)(a) : (uint64_t)(a));
    // public static FFABSU = (a) ((a) <= 0 ? -(unsigned)(a) : (unsigned)(a));
    // public static FFALIGN = (x, a) (((x)+(a)-1)&~((a)-1));
    // public static FFDIFFSIGN = (x,y) (((x)>(y)) - ((x)<(y)));
    /// <summary>FFERROR_BUFFERSRC_EMPTY = FFERRTAG(&apos;M&apos;,&apos;P&apos;,&apos;T&apos;,&apos;Y&apos;)</summary>
    public static readonly int FFERROR_BUFFERSRC_EMPTY = FFERRTAG('M', 'P', 'T', 'Y');
    /// <summary>FFERROR_NOT_READY = FFERRTAG(&apos;N&apos;,&apos;R&apos;,&apos;D&apos;,&apos;Y&apos;)</summary>
    public static readonly int FFERROR_NOT_READY = FFERRTAG('N', 'R', 'D', 'Y');
    // public static FFERRTAG = (a, b, c, d) (-(int)MKTAG(a, b, c, d));
    // public static FFMAX = (a,b) ((a) > (b) ? (a) : (b));
    // public static FFMAX3 = (a,b,c) FFMAX(FFMAX(a,b),c);
    // public static FFMIN = (a,b) ((a) > (b) ? (b) : (a));
    // public static FFMIN3 = (a,b,c) FFMIN(FFMIN(a,b),c);
    // public static FFNABS = (a) ((a) <= 0 ? (a) : (-(a)));
    // public static FFSIGN = (a) ((a) > 0 ? 1 : -1);
    // public static FFSWAP = (type,a,b) do{type SWAP_tmp= b; b= a; a= SWAP_tmp;}while(0);
    // public static FFUDIV = (a,b) (((a)>0 ?(a):(a)-(b)+1) / (b));
    // public static FFUMOD = (a,b) ((a)-(b)*FFUDIV(a,b));
    // public static FILTER_INOUTPADS = (inout, array) .p.inout      = array, .nb_ ## inout = FF_ARRAY_ELEMS(array);
    // public static FILTER_INPUTS = (array) FILTER_INOUTPADS(inputs, (array));
    // public static FILTER_OUTPUTS = (array) FILTER_INOUTPADS(outputs, (array));
    // public static FILTER_PIXFMTS = (...)            FILTER_PIXFMTS_ARRAY(((const enum AVPixelFormat []) { __VA_ARGS__, AV_PIX_FMT_NONE }));
    // public static FILTER_PIXFMTS_ARRAY = (array)    .formats.pixels_list  = array, .formats_state        = FF_FILTER_FORMATS_PIXFMT_LIST;
    // public static FILTER_QUERY_FUNC = (func)        .formats.query_func   = func,  .formats_state        = FF_FILTER_FORMATS_QUERY_FUNC;
    // public static FILTER_QUERY_FUNC2 = (func)       .formats.query_func2  = func,  .formats_state        = FF_FILTER_FORMATS_QUERY_FUNC2;
    // public static FILTER_SAMPLEFMTS = (...)         FILTER_SAMPLEFMTS_ARRAY(((const enum AVSampleFormat[]) { __VA_ARGS__, AV_SAMPLE_FMT_NONE }));
    // public static FILTER_SAMPLEFMTS_ARRAY = (array) .formats.samples_list = array, .formats_state        = FF_FILTER_FORMATS_SAMPLEFMTS_LIST;
    // public static FILTER_SINGLE_PIXFMT = (pix_fmt_)  .formats.pix_fmt = pix_fmt_,    .formats_state   = FF_FILTER_FORMATS_SINGLE_PIXFMT;
    // public static FILTER_SINGLE_SAMPLEFMT = (sample_fmt_) .formats.sample_fmt = sample_fmt_,   .formats_state      = FF_FILTER_FORMATS_SINGLE_SAMPLEFMT;
    // public static GET_UTF16 = (val, GET_16BIT, ERROR)val = (GET_16BIT);{unsigned int hi = val - 0xD800;if (hi < 0x800) {val = (GET_16BIT) - 0xDC00;if (val > 0x3FFU || hi > 0x3FFU){ERROR}val += (hi<<10) + 0x10000;}};
    // public static GET_UTF8 = (val, GET_BYTE, ERROR)val= (GET_BYTE);{uint32_t top = (val & 128) >> 1;if ((val & 0xc0) == 0x80 || val >= 0xFE){ERROR}while (val & top) {unsigned int tmp = (GET_BYTE) - 128;if(tmp>>6){ERROR}val= (val<<6) + tmp;top <<= 5;}val &= (top << 1) - 1;};
    // public static hex_dump_debug = (class, buf, size) do { if (0) av_hex_dump_log(class, AV_LOG_DEBUG, buf, size); } while(0);
    public const int HLS_MAX_AUDIO_SETUP_DATA_LEN = 10;
    public const int HLS_MAX_ID3_TAGS_DATA_LEN = 138;
    public const string ID3v2_DEFAULT_MAGIC = "ID3";
    public const uint ID3v2_FLAG_COMPRESSION = 0x0008;
    public const uint ID3v2_FLAG_DATALEN = 0x0001;
    public const uint ID3v2_FLAG_ENCRYPTION = 0x0004;
    public const uint ID3v2_FLAG_UNSYNCH = 0x0002;
    public const int ID3v2_HEADER_SIZE = 10;
    public const string ID3v2_PRIV_METADATA_PREFIX = "id3v2_priv.";
    public const int INITIAL_BUFFER_SIZE = 32768;
    public static readonly uint LIBAVCODEC_BUILD = LIBAVCODEC_VERSION_INT;
    /// <summary>LIBAVCODEC_IDENT = &quot;Lavc&quot; AV_STRINGIFY(LIBAVCODEC_VERSION)</summary>
    public const string LIBAVCODEC_IDENT = "Lavc" + "LIBAVCODEC_VERSION";
    /// <summary>LIBAVCODEC_VERSION = AV_VERSION(LIBAVCODEC_VERSION_MAJOR,    LIBAVCODEC_VERSION_MINOR,    LIBAVCODEC_VERSION_MICRO)</summary>
    public static readonly string LIBAVCODEC_VERSION = AV_VERSION(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO);
    public static readonly uint LIBAVCODEC_VERSION_INT = AV_VERSION_INT(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO);
    public const uint LIBAVCODEC_VERSION_MAJOR = 62;
    public const uint LIBAVCODEC_VERSION_MICRO = 101;
    public const uint LIBAVCODEC_VERSION_MINOR = 13;
    public static readonly uint LIBAVDEVICE_BUILD = LIBAVDEVICE_VERSION_INT;
    /// <summary>LIBAVDEVICE_IDENT = &quot;Lavd&quot; AV_STRINGIFY(LIBAVDEVICE_VERSION)</summary>
    public const string LIBAVDEVICE_IDENT = "Lavd" + "LIBAVDEVICE_VERSION";
    public static readonly string LIBAVDEVICE_VERSION = AV_VERSION(LIBAVDEVICE_VERSION_MAJOR, LIBAVDEVICE_VERSION_MINOR, LIBAVDEVICE_VERSION_MICRO);
    public static readonly uint LIBAVDEVICE_VERSION_INT = AV_VERSION_INT(LIBAVDEVICE_VERSION_MAJOR, LIBAVDEVICE_VERSION_MINOR, LIBAVDEVICE_VERSION_MICRO);
    public const uint LIBAVDEVICE_VERSION_MAJOR = 62;
    public const uint LIBAVDEVICE_VERSION_MICRO = 100;
    public const uint LIBAVDEVICE_VERSION_MINOR = 2;
    public static readonly uint LIBAVFILTER_BUILD = LIBAVFILTER_VERSION_INT;
    /// <summary>LIBAVFILTER_IDENT = &quot;Lavfi&quot; AV_STRINGIFY(LIBAVFILTER_VERSION)</summary>
    public const string LIBAVFILTER_IDENT = "Lavfi" + "LIBAVFILTER_VERSION";
    /// <summary>LIBAVFILTER_VERSION = AV_VERSION(LIBAVFILTER_VERSION_MAJOR,   LIBAVFILTER_VERSION_MINOR,   LIBAVFILTER_VERSION_MICRO)</summary>
    public static readonly string LIBAVFILTER_VERSION = AV_VERSION(LIBAVFILTER_VERSION_MAJOR, LIBAVFILTER_VERSION_MINOR, LIBAVFILTER_VERSION_MICRO);
    public static readonly uint LIBAVFILTER_VERSION_INT = AV_VERSION_INT(LIBAVFILTER_VERSION_MAJOR, LIBAVFILTER_VERSION_MINOR, LIBAVFILTER_VERSION_MICRO);
    public const uint LIBAVFILTER_VERSION_MAJOR = 11;
    public const uint LIBAVFILTER_VERSION_MICRO = 100;
    public const uint LIBAVFILTER_VERSION_MINOR = 5;
    public static readonly uint LIBAVFORMAT_BUILD = LIBAVFORMAT_VERSION_INT;
    /// <summary>LIBAVFORMAT_IDENT = &quot;Lavf&quot; AV_STRINGIFY(LIBAVFORMAT_VERSION)</summary>
    public const string LIBAVFORMAT_IDENT = "Lavf" + "LIBAVFORMAT_VERSION";
    /// <summary>LIBAVFORMAT_VERSION = AV_VERSION(LIBAVFORMAT_VERSION_MAJOR,   LIBAVFORMAT_VERSION_MINOR,   LIBAVFORMAT_VERSION_MICRO)</summary>
    public static readonly string LIBAVFORMAT_VERSION = AV_VERSION(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO);
    public static readonly uint LIBAVFORMAT_VERSION_INT = AV_VERSION_INT(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO);
    public const uint LIBAVFORMAT_VERSION_MAJOR = 62;
    public const uint LIBAVFORMAT_VERSION_MICRO = 101;
    public const uint LIBAVFORMAT_VERSION_MINOR = 4;
    public static readonly uint LIBAVUTIL_BUILD = LIBAVUTIL_VERSION_INT;
    /// <summary>LIBAVUTIL_IDENT = &quot;Lavu&quot; AV_STRINGIFY(LIBAVUTIL_VERSION)</summary>
    public const string LIBAVUTIL_IDENT = "Lavu" + "LIBAVUTIL_VERSION";
    /// <summary>LIBAVUTIL_VERSION = AV_VERSION(LIBAVUTIL_VERSION_MAJOR,     LIBAVUTIL_VERSION_MINOR,     LIBAVUTIL_VERSION_MICRO)</summary>
    public static readonly string LIBAVUTIL_VERSION = AV_VERSION(LIBAVUTIL_VERSION_MAJOR, LIBAVUTIL_VERSION_MINOR, LIBAVUTIL_VERSION_MICRO);
    public static readonly uint LIBAVUTIL_VERSION_INT = AV_VERSION_INT(LIBAVUTIL_VERSION_MAJOR, LIBAVUTIL_VERSION_MINOR, LIBAVUTIL_VERSION_MICRO);
    public const uint LIBAVUTIL_VERSION_MAJOR = 60;
    public const uint LIBAVUTIL_VERSION_MICRO = 100;
    public const uint LIBAVUTIL_VERSION_MINOR = 10;
    public static readonly uint LIBSWRESAMPLE_BUILD = LIBSWRESAMPLE_VERSION_INT;
    /// <summary>LIBSWRESAMPLE_IDENT = &quot;SwR&quot; AV_STRINGIFY(LIBSWRESAMPLE_VERSION)</summary>
    public const string LIBSWRESAMPLE_IDENT = "SwR" + "LIBSWRESAMPLE_VERSION";
    public static readonly string LIBSWRESAMPLE_VERSION = AV_VERSION(LIBSWRESAMPLE_VERSION_MAJOR, LIBSWRESAMPLE_VERSION_MINOR, LIBSWRESAMPLE_VERSION_MICRO);
    public static readonly uint LIBSWRESAMPLE_VERSION_INT = AV_VERSION_INT(LIBSWRESAMPLE_VERSION_MAJOR, LIBSWRESAMPLE_VERSION_MINOR, LIBSWRESAMPLE_VERSION_MICRO);
    public const uint LIBSWRESAMPLE_VERSION_MAJOR = 6;
    public const uint LIBSWRESAMPLE_VERSION_MICRO = 100;
    public const uint LIBSWRESAMPLE_VERSION_MINOR = 2;
    public static readonly uint LIBSWSCALE_BUILD = LIBSWSCALE_VERSION_INT;
    /// <summary>LIBSWSCALE_IDENT = &quot;SwS&quot; AV_STRINGIFY(LIBSWSCALE_VERSION)</summary>
    public const string LIBSWSCALE_IDENT = "SwS" + "LIBSWSCALE_VERSION";
    public static readonly string LIBSWSCALE_VERSION = AV_VERSION(LIBSWSCALE_VERSION_MAJOR, LIBSWSCALE_VERSION_MINOR, LIBSWSCALE_VERSION_MICRO);
    public static readonly uint LIBSWSCALE_VERSION_INT = AV_VERSION_INT(LIBSWSCALE_VERSION_MAJOR, LIBSWSCALE_VERSION_MINOR, LIBSWSCALE_VERSION_MICRO);
    public const uint LIBSWSCALE_VERSION_MAJOR = 9;
    public const uint LIBSWSCALE_VERSION_MICRO = 100;
    public const uint LIBSWSCALE_VERSION_MINOR = 2;
    public const double M_1_PI = 0.31830988618379067154;
    public const float M_1_PIf = 0.31830988618379067154f;
    public const double M_2_PI = 0.63661977236758134308;
    public const float M_2_PIf = 0.63661977236758134308f;
    public const double M_2_SQRTPI = 1.12837916709551257390;
    public const float M_2_SQRTPIf = 1.12837916709551257390f;
    public const double M_E = 2.7182818284590452354;
    public const float M_Ef = 2.7182818284590452354f;
    public const double M_LN10 = 2.30258509299404568402;
    public const float M_LN10f = 2.30258509299404568402f;
    public const double M_LN2 = 0.69314718055994530942;
    public const float M_LN2f = 0.69314718055994530942f;
    public const double M_LOG2_10 = 3.32192809488736234787;
    public const float M_LOG2_10f = 3.32192809488736234787f;
    public const double M_PHI = 1.61803398874989484820;
    public const float M_PHIf = 1.61803398874989484820f;
    public const double M_PI = 3.14159265358979323846;
    public const double M_PI_2 = 1.57079632679489661923;
    public const float M_PI_2f = 1.57079632679489661923f;
    public const double M_PI_4 = 0.78539816339744830962;
    public const float M_PI_4f = 0.78539816339744830962f;
    public const float M_PIf = 3.14159265358979323846f;
    public const double M_SQRT1_2 = 0.70710678118654752440;
    public const float M_SQRT1_2f = 0.70710678118654752440f;
    public const double M_SQRT2 = 1.41421356237309504880;
    public const float M_SQRT2f = 1.41421356237309504880f;
    public const int MAX_CHARACTERISTICS_LEN = 512;
    public const int MAX_FIELD_LEN = 64;
    public const int MAX_REORDER_DELAY = 16;
    public const int MAX_URL_SIZE = 4096;
    // public static MKBETAG = (a,b,c,d) ((d) | ((c) << 8) | ((b) << 16) | ((unsigned)(a) << 24));
    // public static MKTAG = (a,b,c,d)   ((a) | ((b) << 8) | ((c) << 16) | ((unsigned)(d) << 24));
    public const int MPEG_TIME_BASE = 90000;
    // public static MPEG_TIME_BASE_Q = (AVRational){1, MPEG_TIME_BASE};
    /// <summary>NTP_OFFSET = 2208988800ULL</summary>
    public const ulong NTP_OFFSET = 2208988800UL;
    /// <summary>NTP_OFFSET_US = (NTP_OFFSET * 1000000ULL)</summary>
    public const ulong NTP_OFFSET_US = NTP_OFFSET * 1000000UL;
    /// <summary>PROBE_BUF_MAX = (1 &lt;&lt; 20)</summary>
    public const int PROBE_BUF_MAX = 1 << 20;
    public const int PROBE_BUF_MIN = 2048;
    // public static PUT_UTF16 = (val, tmp, PUT_16BIT){uint32_t in = val;if (in < 0x10000) {tmp = in;PUT_16BIT} else {tmp = 0xD800 | ((in - 0x10000) >> 10);PUT_16BITtmp = 0xDC00 | ((in - 0x10000) & 0x3FF);PUT_16BIT}};
    // public static PUT_UTF8 = (val, tmp, PUT_BYTE){int bytes, shift;uint32_t in = val;if (in < 0x80) {tmp = in;PUT_BYTE} else {bytes = (av_log2(in) + 4) / 5;shift = (bytes - 1) * 6;tmp = (256 - (256 >> bytes)) | (in >> shift);PUT_BYTEwhile (shift >= 6) {shift -= 6;tmp = 0x80 | ((in >> shift) & 0x3f);PUT_BYTE}}};
    // public static ROUNDED_DIV = (a,b) (((a)>=0 ? (a) + ((b)>>1) : (a) - ((b)>>1))/(b));
    // public static RSHIFT = (a,b) ((a) > 0 ? ((a) + ((1<<(b))>>1))>>(b) : ((a) + ((1<<(b))>>1)-1)>>(b));
    public const string SPACE_CHARS = " \t\r\n";
    public const int SWR_FLAG_RESAMPLE = 1;
    public const double SWS_MAX_REDUCE_CUTOFF = 0.002;
    // public static TS2D = (ts)     ((ts) == AV_NOPTS_VALUE ? NAN : (double)(ts));
    // public static TS2T = (ts, tb) ((ts) == AV_NOPTS_VALUE ? NAN : (double)(ts) * av_q2d(tb));
}
